# Generated by Django 5.0.6 on 2026-06-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("principal", "Principal"),
                    ("teacher", "Teacher"),
                    ("accountant", "Accountant"),
                    ("hr", "HR Manager"),
                    ("staff", "Staff"),
                    ("parent", "Parent"),
                    ("student", "Student"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
    ]
