# Generated by Django 5.0.6 on 2026-06-20 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grades",
                to="erp.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="passing_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=50,
                help_text="Minimum percentage required to pass",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="semester",
            field=models.CharField(
                choices=[
                    ("s1", "Semester 1"),
                    ("s2", "Semester 2"),
                    ("mid", "Midterm"),
                    ("final", "Final"),
                ],
                default="s1",
                max_length=10,
            ),
        ),
    ]
