# Generated by Django 5.0.6 on 2026-06-20 08:27

from django.db import migrations, models


def _copy_parent_name_to_father(apps, schema_editor):
    Student = apps.get_model("erp", "Student")
    for s in Student.objects.exclude(parent_name=""):
        s.father_name = s.parent_name
        s.save(update_fields=["father_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0002_grade_academic_year_grade_passing_pct_grade_semester"),
    ]

    operations = [
        # 1) Add father_name first so we can backfill from parent_name
        migrations.AddField(
            model_name="student",
            name="father_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        # 2) Copy existing parent_name → father_name
        migrations.RunPython(
            code=_copy_parent_name_to_father,
            reverse_code=migrations.RunPython.noop,
        ),
        # 3) Now drop the legacy field
        migrations.RemoveField(
            model_name="student",
            name="parent_name",
        ),
        migrations.AddField(
            model_name="student",
            name="district",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="father_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="student",
            name="id_number",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="student",
            name="id_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bi", "BI"),
                    ("electoral", "Electoral"),
                    ("passport", "Passport"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="mother_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="student",
            name="school_certificate",
            field=models.FileField(
                blank=True,
                help_text="Upload the student's last school certificate.",
                null=True,
                upload_to="student_docs/certificates/",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="subdistrict",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="subvillage",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="village",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="teacher",
            name="address",
            field=models.TextField(
                blank=True, help_text="Additional address details (optional)"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="diploma_certificate",
            field=models.FileField(
                blank=True,
                help_text="Upload diploma / certificate scan.",
                null=True,
                upload_to="teacher_docs/diplomas/",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="district",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="teacher",
            name="education_background",
            field=models.TextField(
                blank=True,
                help_text="Schools attended, degrees, certifications, year-by-year.",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="father_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="teacher",
            name="id_number",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="teacher",
            name="id_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bi", "BI"),
                    ("electoral", "Electoral"),
                    ("passport", "Passport"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="mother_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="teacher",
            name="subdistrict",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="teacher",
            name="subvillage",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="teacher",
            name="village",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.TextField(
                blank=True, help_text="Additional address details (optional)"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="qualification",
            field=models.CharField(
                blank=True,
                help_text="Highest qualification, e.g. 'MA Mathematics'",
                max_length=120,
            ),
        ),
    ]
