# Generated by Django 5.0.6 on 2026-06-20 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0004_parent_portal_and_payments"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("html", models.TextField()),
                (
                    "mode",
                    models.CharField(
                        choices=[("mock", "Mock"), ("live", "Live")],
                        default="mock",
                        max_length=10,
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("error", models.CharField(blank=True, max_length=300)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_emails",
                        to="erp.feeinvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
    ]
