# Generated by Django 5.0.6 on 2026-06-20 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0005_sent_email_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_user",
            field=models.OneToOneField(
                blank=True,
                help_text="Student account used to log in to the student portal.",
                limit_choices_to={"role": "student"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reason", models.CharField(max_length=200)),
                ("issued_on", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("applied", "Applied"),
                            ("void", "Void"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional invoice this credit was applied against.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_notes",
                        to="erp.feeinvoice",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_notes",
                        to="erp.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_on", "-id"],
            },
        ),
    ]
