# Generated by Django 5.0.6 on 2026-06-21 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0007_inventorycategory_jobposting_trainingprogram_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="teacher_user",
            field=models.OneToOneField(
                blank=True,
                help_text="Teacher account used to log in to the teacher portal.",
                limit_choices_to={"role": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teacher_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="StudentEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("s1", "Semester 1"),
                            ("s2", "Semester 2"),
                            ("mid", "Midterm"),
                            ("final", "Final"),
                        ],
                        default="s1",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("behaviour", "Behaviour"),
                            ("counselling", "Counselling"),
                            ("recognition", "Recognition / Praise"),
                            ("other", "Other"),
                        ],
                        default="academic",
                        max_length=12,
                    ),
                ),
                ("comment", models.TextField()),
                ("recommendation", models.TextField(blank=True)),
                (
                    "visible_to_parent",
                    models.BooleanField(
                        default=True,
                        help_text="On by default — note appears on the parent + student portals.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations",
                        to="erp.academicyear",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="erp.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations_written",
                        to="erp.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
