# Generated by Django 5.0.6 on 2026-06-21 08:53

import django.db.models.deletion
import erp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0008_teacher_teacher_user_studentevaluation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeachingDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("syllabus", "Syllabus"),
                            ("lesson_plan", "Lesson Plan"),
                            ("handout", "Handout / Worksheet"),
                            ("policy", "School Policy"),
                            ("training", "Training Material"),
                            ("other", "Other"),
                        ],
                        default="syllabus",
                        max_length=12,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="teaching_docs/",
                        validators=[erp.models._validate_pdf],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teaching_documents",
                        to="erp.academicyear",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Pick the subjects this document is for. Leave empty to share with ALL teachers.",
                        related_name="teaching_documents",
                        to="erp.subject",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at", "-id"],
            },
        ),
    ]
