# Generated by Django 5.0.6 on 2026-06-21 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0009_teachingdocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("title_pt", models.CharField(blank=True, max_length=160)),
                ("title_tet", models.CharField(blank=True, max_length=160)),
                ("body", models.TextField()),
                ("body_pt", models.TextField(blank=True)),
                ("body_tet", models.TextField(blank=True)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "Everyone"),
                            ("admin", "Administrators"),
                            ("teacher", "Teachers"),
                            ("parent", "Parents"),
                            ("student", "Students"),
                        ],
                        default="all",
                        max_length=12,
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "audience_classes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Restrict to specific classes (leave empty for all classes in the audience).",
                        to="erp.schoolclass",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_pinned", "-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="English title", max_length=160)),
                (
                    "title_pt",
                    models.CharField(blank=True, help_text="Português", max_length=160),
                ),
                (
                    "title_tet",
                    models.CharField(blank=True, help_text="Tetum", max_length=160),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("t1", "Term 1"),
                            ("t2", "Term 2"),
                            ("t3", "Term 3"),
                            ("s1", "Semester 1"),
                            ("s2", "Semester 2"),
                            ("mid", "Midterm"),
                            ("final", "Final"),
                        ],
                        default="t1",
                        max_length=10,
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(decimal_places=2, default=100, max_digits=6),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Optional reference material for students",
                        null=True,
                        upload_to="assignments/",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("due_at", models.DateTimeField()),
                ("is_published", models.BooleanField(default=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="erp.academicyear",
                    ),
                ),
                (
                    "class_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="erp.schoolclass",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="erp.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="erp.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("title_pt", models.CharField(blank=True, max_length=160)),
                ("title_tet", models.CharField(blank=True, max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("holiday", "Holiday"),
                            ("exam", "Exam"),
                            ("meeting", "Meeting"),
                            ("training", "Training"),
                            ("event", "School Event"),
                            ("deadline", "Deadline"),
                            ("other", "Other"),
                        ],
                        default="event",
                        max_length=12,
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("all_day", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=120)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "Everyone"),
                            ("admin", "Administrators"),
                            ("teacher", "Teachers"),
                            ("parent", "Parents"),
                            ("student", "Students"),
                        ],
                        default="all",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "audience_classes",
                    models.ManyToManyField(blank=True, to="erp.schoolclass"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["start_at"],
            },
        ),
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_answer", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="submissions/"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="erp.assignment",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="erp.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "unique_together": {("assignment", "student")},
            },
        ),
    ]
