# Generated by Django 5.0.6 on 2026-06-21 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0010_announcement_assignment_calendarevent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("title_pt", models.CharField(blank=True, max_length=160)),
                ("title_tet", models.CharField(blank=True, max_length=160)),
                (
                    "week_start",
                    models.DateField(help_text="Monday of the week this plan covers."),
                ),
                (
                    "objectives",
                    models.TextField(
                        blank=True, help_text="Learning objectives for the week."
                    ),
                ),
                (
                    "activities",
                    models.TextField(
                        blank=True,
                        help_text="Topics and activities, day-by-day if useful.",
                    ),
                ),
                (
                    "materials",
                    models.TextField(
                        blank=True, help_text="Books, handouts, equipment."
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Optional PDF / document upload.",
                        null=True,
                        upload_to="lesson_plans/",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Hide drafts from admin/principal view."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plans",
                        to="erp.schoolclass",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plans",
                        to="erp.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plans",
                        to="erp.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StudentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("bi", "BI / Electoral Card"),
                            ("birth", "Birth Certificate"),
                            ("baptism", "Baptism Certificate"),
                            ("vaccination", "Vaccination Card"),
                            ("passport", "Passport"),
                            ("transfer", "Transfer Certificate"),
                            ("prior_report", "Previous School Report"),
                            ("photo", "ID Photo"),
                            ("parent_id", "Parent Identification"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional descriptive label (e.g. 'BI 2024')",
                        max_length=160,
                    ),
                ),
                ("file", models.FileField(upload_to="student_docs/")),
                ("issued_date", models.DateField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateField(
                        blank=True,
                        help_text="Useful for BI / Passport — flags expiring docs.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="erp.student",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_student_docs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at", "-id"],
            },
        ),
    ]
