# Generated by Django 5.0.6 on 2026-06-21 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0011_lessonplan_studentdocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("title_pt", models.CharField(blank=True, max_length=160)),
                ("title_tet", models.CharField(blank=True, max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("link", "External Link"),
                            ("pdf", "PDF / Document"),
                            ("slides", "Slides"),
                            ("other", "Other"),
                        ],
                        default="link",
                        max_length=10,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="YouTube/Vimeo URL for videos, or any external link.",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="learning_materials/"
                    ),
                ),
                (
                    "week_no",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional — week / module number for grouping.",
                        null=True,
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_room",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty to share with every class taking this subject.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="erp.schoolclass",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="erp.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials",
                        to="erp.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["subject__name", "week_no", "-created_at"],
            },
        ),
    ]
