# Generated by Django 5.0.6 on 2026-06-21 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0012_learningmaterial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_viewed_at", models.DateTimeField(auto_now_add=True)),
                ("last_viewed_at", models.DateTimeField(auto_now=True)),
                ("view_count", models.PositiveIntegerField(default=1)),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="erp.learningmaterial",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_views",
                        to="erp.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_viewed_at"],
                "unique_together": {("student", "material")},
            },
        ),
    ]
